apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-front-cluster-ip
  labels:
    app: front
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: front
  type: ClusterIP