apiVersion: v1
kind: Secret
metadata:
  name: front-secret
data:
  AUTH_SECRET: {{ .Values.front.auth_secret | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.front.google_client_id | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.front.google_client_secret | b64enc }}
