apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-gateway-deployment
  labels:
    app: gateway
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: zzingo5/fc-nestjs-gateway:latest
          name: gateway-container
          envFrom:
            - configMapRef:
                name: gateway-config-map
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5
