apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-gateway-cluster-ip
  labels:
    app: gateway
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: gateway
  type: ClusterIP