apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        # 기타 HTTP 설정

        server {
            listen 80;

            location / {
                default_type text/plain;
                return 200 "$hostname\n";
            }
        }
    }
