apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-user-cluster-ip
  labels:
    app: user
spec:
  ports:
    - port: 4001
      protocol: TCP
      targetPort: 4001
  selector:
    app: user
  type: ClusterIP