apiVersion: v1
kind: Secret
metadata:
  name: user-secret
data:
  DB_URL: { { .Values.user.db_url | b64enc } }
  ACCESS_TOKEN_SECRET: { { .Values.user.access_token_secret | b64enc } }
  REFRESH_TOKEN_SECRET: { { .Values.user.refresh_token_secret | b64enc } }
  TOKEN_EXPIRE_TIME: { { .Values.user.token_expire_time | b64enc } }
  GOOGLE_CLIENT_ID: { { .Values.user.google_client_id | b64enc } }
  GOOGLE_CLIENT_SECRET: { { .Values.user.google_client_secret | b64enc } }
