apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-payment-deployment
  labels:
    app: payment
spec:
  replicas: {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      app: payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: zzingo5/fc-nestjs-payment:latest
          name: payment-container
          envFrom:
            - configMapRef:
                name: payment-config-map
            - secretRef:
                name: payment-secret
          ports:
            - containerPort: 3001
          livenessProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3001              
            periodSeconds: 5
