apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-album-cluster-ip
  labels:
    app: album
spec:
  ports:
    - port: 4002
      protocol: TCP
      targetPort: 4002
  selector:
    app: album
  type: ClusterIP