apiVersion: v1
kind: Secret
metadata:
  name: album-secret
data:
  DB_URL: {{ .Values.album.db_url | b64enc }}
  RABBITMQ_URL: {{ .Values.album.rabbitmq_url | b64enc }}
  MINIO_ENDPOINT: {{ .Values.album.minio_endpoint | b64enc }}
  MINIO_PORT: {{ .Values.album.minio_port | quote | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.album.minio_access_key | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.album.minio_secret_key | b64enc }}
  MINIO_BUCKET_NAME: {{ .Values.album.minio_bucket_name | b64enc }}
