apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hatongsu-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.practice-zzingo.net
        - api.practice-zzingo.net
      secretName: hatongsu-tls-secret
  rules:
    - host: www.practice-zzingo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-front-cluster-ip
                port:
                  number: 3000
    - host: api.practice-zzingo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-gateway-cluster-ip
                port:
                  number: 4000
          
