apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hatongsu-tls
  namespace: hatongsu
spec:
  secretName: hatongsu-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: practice-zzingo.net
  dnsNames:
    - www.practice-zzingo.net
    - api.practice-zzingo.net
  acme:
    config:
      - http01:
          ingressClass: nginx
