gateway:
  replicas: 1
  image:
    repository: zzingo5/fc-nestjs-gateway
    tag: latest

notification:
  replicas: 1
  image:
    repository: zzingo5/fc-nestjs-notification
    tag: latest
  db_url: "mongodb://foo:bar@example.com/notification?authSource=admin"

order:
  replicas: 1
  image:
    repository: zzingo5/fc-nestjs-order
    tag: latest
  db_url: "mongodb://foo:bar@example.com/order?authSource=admin"

payment:
  replicas: 1
  image:
    repository: zzingo5/fc-nestjs-payment
    tag: latest
  db_url: "postgresql://foo:bar@example.com:15432/payment"

product:
  replicas: 1
  image:
    repository: zzingo5/fc-nestjs-product
    tag: latest
  db_url: "postgresql://foo:bar@example.com:15432/product"

user:
  replicas: 1
  image:
    repository: zzingo5/fc-nestjs-user
    tag: latest
  db_url: "postgresql://foo:bar@example.com:15432/user"
