apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-notification-cluster-ip
  labels:
    app: notification
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: notification
  type: ClusterIP